service: my-api
frameworkVersion: '3'

custom:
    bundle:
        linting: false
        excludeFiles: '**/*.test.ts'
    serverless-offline:
        httpPort: 8080
        noPrependStageInUrl: true
        reloadHandler: true

provider:
    name: aws
    runtime: nodejs16.x
    stage: ${opt:stage, 'offline'}
    region: us-west-2
    memorySize: 512
    timeout: 10
    logRetentionInDays: 90
    logs:
        httpApi: true
    httpApi:
        cors: true

functions:
    app:
        handler: src/handler.handler
        events:
          - httpApi:
              path: '/{proxy+}'
              method: '*'

plugins:
    - serverless-dotenv-plugin
    - serverless-bundle
    - serverless-offline
